services:
  - type: web
    name: bigezo-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: bigezo-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bigezo-db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bigezo-db
          property: password
    plan: free
    numInstances: 1

databases:
  - name: bigezo-db
    databaseName: bigezo
    user: bigezo_user
    plan: free
    deleteProtection: true
